#!/bin/bash

# Prova batch file

PROVA_HOME="../.."
PROVA_LIBS="$PROVA_HOME/lib"

# Building the Classpath
CLASSPATH="$CLASSPATH:$PROVA_HOME/target/*"
CLASSPATH="$CLASSPATH:$PROVA_LIBS/*"

export CLASSPATH 

java -Xms512m -Xmx512m -XX:NewSize=256m -XX:MaxNewSize=256m org.provarules.api2.ProvaCommunicatorImpl prova password $*
